import type { Prompt } from "../domain/models.js";

export interface ButtonsSwitchboardPayload {
  id: string;
  title: string;
  description?: string;
  icon?: string;
  context: { type: "global" };
  triggers: Array<{ type: "palette" } | { type: "inline"; command: string }>;
  isEnabled: boolean;
  placement: {
    mode: "floating" | "window";
    anchor: "screen" | "window";
    position: { x: number; y: number; unit: "px" | "percent" };
    size: { width: number; height: number; unit: "px" | "percent" };
    opacity?: number;
    alwaysOnTop?: boolean;
    transparent?: boolean;
  };
  switchboard: {
    tileSize: "xs" | "sm" | "md" | "lg";
    allowSearch?: boolean;
    phrases: Array<{ id: string; label: string; value: string }>;
  };
}

export interface PlannerBucketDraft {
  name: string;
  source: "prompt-vault";
  tags: string[];
  tasks: Array<{
    title: string;
    note?: string;
    tags: string[];
  }>;
}

export function buildButtonsSwitchboardPayload(
  prompts: readonly Prompt[],
  limit = 12
): ButtonsSwitchboardPayload | null {
  const phrases = prompts
    .filter((p) => p.latestVersion?.body)
    .slice(0, limit)
    .map((p, idx) => ({
      id: p.id ?? `pv-${idx}`,
      label: p.title ?? p.slug,
      value: p.latestVersion?.body ?? "",
    }));

  if (phrases.length === 0) return null;

  return {
    id: `pv-switchboard-${Date.now()}`,
    title: "Prompt Vault Quick Phrases",
    description: "Autogenerated from Prompt Vault content for use in Buttons.",
    icon: "keyboard",
    context: { type: "global" },
    triggers: [{ type: "palette" }],
    isEnabled: true,
    placement: {
      mode: "floating",
      anchor: "screen",
      position: { x: 14, y: 18, unit: "percent" },
      size: { width: 400, height: 320, unit: "px" },
      opacity: 0.92,
      alwaysOnTop: true,
      transparent: true,
    },
    switchboard: {
      tileSize: "sm",
      allowSearch: true,
      phrases,
    },
  };
}

export function buildPlannerBucketDraft(
  prompts: readonly Prompt[],
  limit = 10
): PlannerBucketDraft | null {
  const tasks = prompts.slice(0, limit).map((p) => ({
    title: `Use: ${p.title}`,
    note: p.latestVersion?.body?.slice(0, 360),
    tags: ["prompt-vault", ...(p.tags ?? []).map((t) => t.label ?? "").filter(Boolean)],
  }));

  if (tasks.length === 0) return null;

  return {
    name: "Prompt Vault Picks",
    source: "prompt-vault",
    tags: ["prompt-vault", "import"],
    tasks,
  };
}
