[package]
name = "nw-secrets"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "nw_secrets"
path = "src/lib.rs"

[dependencies]
base64 = "0.21"
cfg-if = "1.0"
thiserror = "1.0"

[target.'cfg(not(windows))'.dependencies]
aes-gcm = "0.10"
keyring = "2.3"
rand = "0.8"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
  "Win32_Security_Cryptography",
  "Win32_System_Memory",
  "Win32_Foundation",
] }
